# Generated by Django 6.0.6 on 2026-06-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('reason', models.TextField()),
                ('summary', models.TextField()),
                ('link', models.URLField(max_length=1000)),
                ('pub_date', models.CharField(blank=True, max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
